name: Release

on:
  push:
    tags: ['v*.*.*']

jobs:
  release:
    name: GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: spenserblack/actions-tag-to-release@v1
        with:
          prerelease: auto

  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - run: bundle install
      - name: Publish to GitHub Package Registry
        env:
          GEM_HOST_API_KEY: "Bearer ${{ secrets.GITHUB_TOKEN }}"
          OWNER: ${{ github.repository_owner }}
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
